package:
  name: cpp_pe_extension
  version: 1.0.0

source:
  git_url: git@github.com:korem-lab/CPP-PE-Extension.git
  git_rev: deployable
  sha256: +q5lQalaUaR1KsEbEfD1ODHbWfGZYIBVNIrL+Kxb+WQ

requirements:
  build:
    - gcc
    - make
    - bzip2
    - zlib >=1.2.12,<1.3.0a0
    - ncurses
    - htslib >=1.18,<1.19.0a0
    - shellinford=1.0

  run:
    - gcc
    - make
    - bzip2
    - zlib
    - ncurses
    - htslib
    - shellinford

about:
  home: 
  description: pair-end extension
  license: unknown
